### ISSUE TITLE
streamline adding new data sources

### ISSUE THREAD

**Issue by ebrahimebrahim** [KitwareMedical/lungair-fhir-server#6]
Messing with our argparse should not be necessary for a user of our API who wants to add a custom data source.
In fact it's best if they don't have to touch `populate_fhir_server.py` at all.

Options:
- make it possible to somehow "register" the new data source once it's created, so that it becomes an option when running `populate_fhir_server.py`.
- make `populate_fhir_server.py` take an argument that somehow points to the custom classes

For a custom data source it would be nice to be able to tell users "create your data source definition like this and then feed it into our tool", rather than saying "fork this project and make these changes."

**Comment by stephencrowell** [comment]
After discussing with @ebrahimebrahim, each implementation of data source will have their own json file to be passed as an argument with fhir server url. The json file will handle importing the required class and creating an instance of the class. Example using `mimic3` shown below. 

```json
{
  "args":
  {
    "mimic3_data_dir": "./path/to/Mimic3/data",
    "mimic3_schemas_dir": "./path/to/Mimic3/schema"
  },
  "class_name": "Mimic3",
  "module_name": "mimic3"
}
```
