### ISSUE TITLE
streamline adding new observation types

### ISSUE THREAD

**Issue by ebrahimebrahim** [KitwareMedical/lungair-fhir-server#7]
Need to think about how to approach this.

One thing I am noticing is the way information is grouped in `UNIT_CODES`, `LOINC_CODES`, and `DISPLAY_STRINGS`, for example. Right now if I wanted to add a new observation type I'd have to go touch each of those and add my entry. It would be better if things were grouped such that the changes I need to make are more localized.

Even better if we can come up with a way to add custom observation types without touching the main code.
Similarly to #6, it would be ideal if users can use our tool directly rather than having to fork it if they want to add their own observation type. We need to think about how we can design it this way.

**Comment by stephencrowell** [comment]
After discussing with @ebrahimebrahim, creating a json file of observations can take over the enum and dicts used currently. Abstract `Observation` class will read the json file into a dict and the functions formally using dicts (`get_display_string`, `get_unit_code`, etc.) will use the new dict from the json file. Example is shown below for heart rate observations.

```json
{
  "HR": 
  {
    "display_string": "Heart Rate",
    "unit_code": "/min",
    "loinc_code": "8867-4"
  },
}
```
